name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the client dev docker image to run test.
      run: docker build -t docker-client -f ./client/Dockerfile.dev .
    - name: Running the client dev docker image.
      run: docker run -e CI=true docker-client npm test

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

