name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the client dev docker image to run test.
      run: docker build -t docker-client -f ./client/Dockerfile.dev ./client
    - name: Running the client dev docker image.
      run: docker run -e CI=true docker-client npm test

    - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the docker image
      run: docker build -t docker-client ./client
      run: docker build -t docker-server ./server
      run: docker build -t docker-worker ./worker
      run: docker build -t docker-nginx ./nginx

    - name: Docker push
      run: docker push ${{secret.DOCKER_USERNAME}}/docker_client

    # - name: Generate deployment package
    #   run: zip -r deploy.zip . -x '*.git*'

