name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the client dev docker image to run test.
      run: docker build -t docker-client -f ./client/Dockerfile.dev ./client
    - name: Running the client dev docker image.
      run: docker run -e CI=true docker-client npm test

    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the docker image
      run: | 
        docker build -t ${{secrets.DOCKER_USERNAME}}/docker-client ./client
        docker build -t ${{secrets.DOCKER_USERNAME}}/docker-server ./server
        docker build -t ${{secrets.DOCKER_USERNAME}}/docker-worker ./worker
        docker build -t ${{secrets.DOCKER_USERNAME}}/docker-nginx ./nginx

    - name: Docker push
      run: | 
        docker push ${{secrets.DOCKER_USERNAME}}/docker-client
        docker push ${{secrets.DOCKER_USERNAME}}/docker-server
        docker push ${{secrets.DOCKER_USERNAME}}/docker-worker
        docker push ${{secrets.DOCKER_USERNAME}}/docker-nginx

    - name: Generate deployment package
      run: zip -r fibCalcDeploy.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: Fibonacci-Calculator
        environment_name: Fibonacci-Calculator-env
        version_label: 125
        region: ap-south-1
        deployment_package: fibCalcDeploy.zip