name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the client dev docker image to run test.
      run: docker build -t docker-client -f ./client/Dockerfile.dev ./client
    - name: Running the client dev docker image.
      run: docker run -e CI=true docker-client npm test

    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the docker image
      run: | 
        docker build -t docker-client ./client
        docker build -t docker-server ./server
        docker build -t docker-worker ./worker
        docker build -t docker-nginx ./nginx

    - name: Docker push
      run: | 
        docker push ${{secrets.DOCKER_USERNAME}}/docker_client
        docker push ${{secrets.DOCKER_USERNAME}}/docker_server
        docker push ${{secrets.DOCKER_USERNAME}}/docker_worker
        docker push ${{secrets.DOCKER_USERNAME}}/docker_nginx

    # - name: Generate deployment package
    #   run: zip -r deploy.zip . -x '*.git*'

